services:
  php:
    image: yiisoftware/yii2-php:8.4-fpm-nginx
    container_name: knowledge-yii2
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'

  mysql:
    image: mysql:8
    container_name: knowledge-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'sofj@LA@451@#l'
      MYSQL_DATABASE: 'workslavan'
      MYSQL_USER: 'workslavan'
      MYSQL_PASSWORD: 'sofj@LA@451@#l'
    volumes:
      - ./sourcefiles/dbdata/data:/var/lib/mysql
    ports:
      - '3306:3306'
